export const initialNodes = [
    {
        id: 'strategic',
        type: 'group',
        data: {
            category: 'Strategic',
            type: 'group',
        },
        position: { x: 0, y: -480 },
        style: { width: 2500, height: 430, backgroundColor: 'rgba(0, 255, 0, 0.1)' },
        draggable: false
    },
    {
        id: 'managerial',
        type: 'group',
        data: {
            category: 'Managerial',
            type: 'group',
        },
        position: { x: 0, y: 0 },
        style: { width: 2500, height: 430, backgroundColor: 'rgba(0, 0, 255, 0.1)' },
        draggable: false
    },
    {
        id: 'operational',
        type: 'group',
        data: {
            category: 'Operational',
            type: 'group',
        },
        position: { x: 0, y: 480 },
        style: { width: 2500, height: 430, backgroundColor: 'rgba(255, 0, 0, 0.1)' },
        draggable: false
    },
    {
        id: 'o1',
        type: "kpiNode",
        data: {
            label: 'Taux de comptes conformes au principe "least privilege"',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o2',
        type: "kpiNode",
        data: {
            label: 'Taux de comptes inactifs supprimés',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o3',
        type: "kpiNode",
        data: {
            label: 'Taux d’implémentation du MFA',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o4',
        type: "kpiNode",
        data: {
            label: 'Taux de revue des comptes à privilèges',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o5',
        type: "kpiNode",
        data: {
            label: 'Taux de comptes génériques',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o6',
        type: "kpiNode",
        data: {
            label: 'Temps moyen de révocation des accès',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o7',
        type: "kpiNode",
        data: {
            label: 'Taux de données sensibles chiffrées',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o8',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture du DLP',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o9',
        type: "kpiNode",
        data: {
            label: 'Taux d’assets critiques chiffrés',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o10',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture Antivirus',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o11',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture EDR',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o12',
        type: "kpiNode",
        data: {
            label: 'Taux d’obsolescence global',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o13',
        type: "kpiNode",
        data: {
            label: 'Taux d’obsolescence par systèmes',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o14',
        type: "kpiNode",
        data: {
            label: 'Taux de systèmes critiques avec obsolescence critique',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o15',
        type: "kpiNode",
        data: {
            label: 'Taux de dérogations contrôlées',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o16',
        type: "kpiNode",
        data: {
            label: 'Taux de changements contrôlés',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o17',
        type: "kpiNode",
        data: {
            label: 'Taux d’inspection du trafic sortant (messagerie)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o18',
        type: "kpiNode",
        data: {
            label: 'Taux de spams identifiés',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o19',
        type: "kpiNode",
        data: {
            label: 'Nombre de spams remontés par les collaborateurs',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o20',
        type: "kpiNode",
        data: {
            label: 'Taux de scan code source des applications',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o21',
        type: "kpiNode",
        data: {
            label: 'Taux d’assets critiques contrôlés (Pentests/Scans)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o22',
        type: "kpiNode",
        data: {
            label: 'Taux de projets techniquement contrôlés avant MEP',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o23',
        type: "kpiNode",
        data: {
            label: 'Taux de vulnérabilités pour les assets critiques',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o24',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des scans de vulnérabilités',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o25',
        type: "kpiNode",
        data: {
            label: 'Nombre de vulnérabilités enregistrées par sévérité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o26',
        type: "kpiNode",
        data: {
            label: 'Répartition des vulnérabilités identifiées par catégorie',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o27',
        type: "kpiNode",
        data: {
            label: 'Taux de correction des vulnérabilités',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o28',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture SOC global',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o29',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture SOC par catégorie d’assets',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o30',
        type: "kpiNode",
        data: {
            label: 'Répartition des incidents par étape MITRE ATT&CK',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o31',
        type: "kpiNode",
        data: {
            label: 'Répartition des incidents par criticité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o32',
        type: "kpiNode",
        data: {
            label: 'Répartition des incidents collectés par typologie',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o33',
        type: "kpiNode",
        data: {
            label: 'Taux de faux positifs',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o34',
        type: "kpiNode",
        data: {
            label: 'Taux de prise en charge des alertes dans les délais',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o35',
        type: "kpiNode",
        data: {
            label: 'Taux de traitement des incidents dans les délais',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o36',
        type: "kpiNode",
        data: {
            label: 'Temps moyen de qualification des incidents',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o37',
        type: "kpiNode",
        data: {
            label: 'Temps moyen de traitement des incidents',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o38',
        type: "kpiNode",
        data: {
            label: 'Temps moyen de mise en place des plans de mitigation',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o39',
        type: "kpiNode",
        data: {
            label: 'Taux de remontées avérées couvertes par SOP',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o40',
        type: "kpiNode",
        data: {
            label: 'Taux d’incidents de sécurité du Cloud externe',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o41',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des uses cases actuels',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'o42',
        type: "kpiNode",
        data: {
            label: 'Taux d’implémentation des uses cases SIEM',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    },
    {
        id: 'm1',
        type: "kpiNode",
        data: {
            label: 'Taux de conformité par loi et norme SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm2',
        type: "kpiNode",
        data: {
            label: 'Taux d’avancement des travaux de revue des lois et normes',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm3',
        type: "kpiNode",
        data: {
            label: 'Taux d’avancement des chantiers de mise/maintien en conformité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm4',
        type: "kpiNode",
        data: {
            label: 'Taux de conformité à la PSI Entreprise et directives internes',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm5',
        type: "kpiNode",
        data: {
            label: 'Taux de revue de la PSI et directives internes',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm6',
        type: "kpiNode",
        data: {
            label: 'Niveau de maturité cyber (ISO27001)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm7',
        type: "kpiNode",
        data: {
            label: 'Taux de suivi global des sessions de sensibilisation SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm8',
        type: "kpiNode",
        data: {
            label: 'Taux de réalisation de la feuille de route de sensibilisation',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm9',
        type: "kpiNode",
        data: {
            label: 'Taux de réussite au questionnaire SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm10',
        type: "kpiNode",
        data: {
            label: 'Taux d’échecs aux campagnes phishing',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm11',
        type: "kpiNode",
        data: {
            label: 'Taux de collaborateurs ayant fourni des infos sensibles (phishing)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm12',
        type: "kpiNode",
        data: {
            label: 'Taux de collaborateurs ayant remonté une alerte (phishing)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm13',
        type: "kpiNode",
        data: {
            label: 'Statut de l’analyse de risque SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm14',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des risques par famille',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm15',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des risques par criticité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm16',
        type: "kpiNode",
        data: {
            label: 'Taux d’avancement des plans de traitement des risques',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm17',
        type: "kpiNode",
        data: {
            label: 'Taux de contribution des use cases à la couverture des risques',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm18',
        type: "kpiNode",
        data: {
            label: 'Répartition des données Cloud par criticité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm19',
        type: "kpiNode",
        data: {
            label: 'Taux d’intégration de la sécurité dans les projets',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm20',
        type: "kpiNode",
        data: {
            label: 'Taux d’analyse de risque SSI projet',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm21',
        type: "kpiNode",
        data: {
            label: 'Taux de conformité global des scans code source',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm22',
        type: "kpiNode",
        data: {
            label: 'Taux des tiers évalués avant contractualisation',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm23',
        type: "kpiNode",
        data: {
            label: 'Score moyen des tiers pré-contractualisation',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm24',
        type: "kpiNode",
        data: {
            label: 'Taux de prestataires critiques audités',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm25',
        type: "kpiNode",
        data: {
            label: 'Score moyen SSI des tiers critiques post-audit',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm26',
        type: "kpiNode",
        data: {
            label: 'Turnover des ressources SSI internes',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm27',
        type: "kpiNode",
        data: {
            label: 'Charge prévisionnelle du pôle SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm28',
        type: "kpiNode",
        data: {
            label: 'Répartition de la charge globale (BUILD/RUN)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm29',
        type: "kpiNode",
        data: {
            label: 'Forecast du pôle SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm30',
        type: "kpiNode",
        data: {
            label: 'Suivi global du statut des projets SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm31',
        type: "kpiNode",
        data: {
            label: 'Suivi des 5 projets SSI phares',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm32',
        type: "kpiNode",
        data: {
            label: 'Indice de performance de la fonction de détection',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm33',
        type: "kpiNode",
        data: {
            label: 'Indice de performance de la fonction de réaction',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm34',
        type: "kpiNode",
        data: {
            label: 'Indice de protection des assets',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm35',
        type: "kpiNode",
        data: {
            label: 'Indice de perméabilité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 'm36',
        type: "kpiNode",
        data: {
            label: 'Indice d’exposition aux risques cyber',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'managerial',
        extent: 'parent',
    },
    {
        id: 's1',
        type: "kpiNode",
        data: {
            label: 'Indice de Performance de la fonction de Détection',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's2',
        type: "kpiNode",
        data: {
            label: 'Indice de Performance de la fonction de Réaction',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's3',
        type: "kpiNode",
        data: {
            label: 'Indice de Protection des assets',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's4',
        type: "kpiNode",
        data: {
            label: 'Indice de Perméabilité',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's5',
        type: "kpiNode",
        data: {
            label: 'Indice d’exposition aux risques cyber',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's6',
        type: "kpiNode",
        data: {
            label: 'Part budget dédié à la sécurité SI vs pratiques marché',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's7',
        type: "kpiNode",
        data: {
            label: 'Répartition budget CAPEX - OPEX',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's8',
        type: "kpiNode",
        data: {
            label: 'Répartition du budget cyber par domaine',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's9',
        type: "kpiNode",
        data: {
            label: 'Consommation du budget run vs build',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's10',
        type: "kpiNode",
        data: {
            label: 'Return On Security Investments (ROSI) d’une solution déployée',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's11',
        type: "kpiNode",
        data: {
            label: 'Taux de conformité global aux lois et normes SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's12',
        type: "kpiNode",
        data: {
            label: 'Taux de conformité par loi et normes SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's13',
        type: "kpiNode",
        data: {
            label: 'Niveau de maturité cyber par rapport au référentiel ISO27001',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's14',
        type: "kpiNode",
        data: {
            label: 'Suivi global du statut des projets/programmes au niveau du pôle',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's15',
        type: "kpiNode",
        data: {
            label: 'Taux d’intégration de la sécurité au niveau des projets (SI, réseau, digital)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's16',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture SOC global',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's17',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des uses cases actuels',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's18',
        type: "kpiNode",
        data: {
            label: 'Taux d’implémentation des uses cases',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's19',
        type: "kpiNode",
        data: {
            label: 'Taux de faux positifs',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's20',
        type: "kpiNode",
        data: {
            label: 'Taux de remontées avérées couvertes par une procédure standard de réaction (SOP)',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's21',
        type: "kpiNode",
        data: {
            label: 'Temps moyen de mise en place des plans de mitigation des incidents',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's22',
        type: "kpiNode",
        data: {
            label: 'Taux de prise en charge des alertes dans les délais',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's23',
        type: "kpiNode",
        data: {
            label: 'Taux de traitement des incidents dans les délais',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's24',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des solutions Antivirus avec version à jour',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's25',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture de solutions EDR au niveau des endpoints',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's26',
        type: "kpiNode",
        data: {
            label: 'Taux d’implémentation du MFA',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's27',
        type: "kpiNode",
        data: {
            label: 'Taux de couverture des scans de sécurité et tests d’intrusion',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's28',
        type: "kpiNode",
        data: {
            label: 'Taux de spams remontés par les collaborateurs',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's29',
        type: "kpiNode",
        data: {
            label: 'Taux d’obsolescence global',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's30',
        type: "kpiNode",
        data: {
            label: 'Taux de vulnérabilités pour les assets critiques',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's31',
        type: "kpiNode",
        data: {
            label: 'Taux de systèmes critiques avec obsolescence critique',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's32',
        type: "kpiNode",
        data: {
            label: 'Statut de l’analyse de risque SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's33',
        type: "kpiNode",
        data: {
            label: 'Taux de risques critiques non couverts',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
    {
        id: 's34',
        type: "kpiNode",
        data: {
            label: 'Taux de suivi global des sessions sensibilisations SSI',
            description: 'Percentage of accounts compliant with least privilege security principle',
            category: 'operational',
        },
        parentId: 'strategic',
        extent: 'parent',
    },
];

export const initialEdges = [
    { id: 'e1', source: 'm10', target: 'm11' },
    { id: 'e2', source: 'm10', target: 'm12' },
    { id: 'e3', source: 'm13', target: 'o17' },
    { id: 'e4', source: 'm13', target: 'o20' },
    { id: 'e5', source: 'm13', target: 'o21' },
    { id: 'e6', source: 'm13', target: 'o22' },
    { id: 'e7', source: 'm13', target: 'o27' },
    { id: 'e8', source: 'm13', target: 'o28' },
    { id: 'e9', source: 'm13', target: 'o33' },
    { id: 'e10', source: 'm14', target: 'o1' },
    { id: 'e11', source: 'm14', target: 'o2' },
    { id: 'e12', source: 'm14', target: 'o7' },
    { id: 'e13', source: 'm14', target: 'o8' },
    { id: 'e14', source: 'm14', target: 'o9' },
    { id: 'e15', source: 'm14', target: 'o10' },
    { id: 'e16', source: 'm14', target: 'o11' },
    { id: 'e17', source: 'm14', target: 'o17' },
    { id: 'e18', source: 'm14', target: 'o18' },
    { id: 'e19', source: 'm14', target: 'o30' },
    { id: 'e20', source: 'm14', target: 'o31' },
    { id: 'e21', source: 'm14', target: 'o32' },
    { id: 'e22', source: 'm15', target: 'o1' },
    { id: 'e23', source: 'm15', target: 'o2' },
    { id: 'e24', source: 'm15', target: 'o7' },
    { id: 'e25', source: 'm15', target: 'o8' },
    { id: 'e26', source: 'm15', target: 'o9' },
    { id: 'e27', source: 'm15', target: 'o10' },
    { id: 'e28', source: 'm15', target: 'o11' },
    { id: 'e29', source: 'm15', target: 'o17' },
    { id: 'e30', source: 'm15', target: 'o18' },
    { id: 'e31', source: 'm15', target: 'o30' },
    { id: 'e32', source: 'm15', target: 'o31' },
    { id: 'e33', source: 'm15', target: 'o32' },
    { id: 'e34', source: 'm16', target: 'o8' },
    { id: 'e35', source: 'm16', target: 'o10' },
    { id: 'e36', source: 'm16', target: 'o11' },
    { id: 'e37', source: 'm16', target: 'o24' },
    { id: 'e38', source: 'm16', target: 'o28' },
    { id: 'e39', source: 'm16', target: 'o34' },
    { id: 'e40', source: 'm16', target: 'o35' },
    { id: 'e41', source: 'm16', target: 'o36' },
    { id: 'e42', source: 'm16', target: 'o37' },
    { id: 'e43', source: 'm16', target: 'o38' },
    { id: 'e44', source: 'm17', target: 'o41' },
    { id: 'e45', source: 'm19', target: 'o22' },
    { id: 'e46', source: 'm19', target: 'm20' },
    { id: 'e47', source: 'm21', target: 'o20' },
    { id: 'e48', source: 'm23', target: 'm22' },
    { id: 'e49', source: 'm30', target: 'm2' },
    { id: 'e50', source: 'm30', target: 'm3' },
    { id: 'e51', source: 'm32', target: 'o33' },
    { id: 'e52', source: 'm33', target: 'o34' },
    { id: 'e53', source: 'm33', target: 'o35' },
    { id: 'e54', source: 'm33', target: 'o36' },
    { id: 'e55', source: 'm33', target: 'o37' },
    { id: 'e56', source: 'm33', target: 'o38' },
    { id: 'e57', source: 'm33', target: 'o39' },
    { id: 'e58', source: 'm33', target: 'o40' },
    { id: 'e59', source: 'm34', target: 'o3' },
    { id: 'e60', source: 'm34', target: 'o7' },
    { id: 'e61', source: 'm34', target: 'o8' },
    { id: 'e62', source: 'm34', target: 'o9' },
    { id: 'e63', source: 'm34', target: 'o10' },
    { id: 'e64', source: 'm34', target: 'o11' },
    { id: 'e65', source: 'm34', target: 'o24' },
    { id: 'e66', source: 'm34', target: 'o28' },
    { id: 'e67', source: 'm34', target: 'o29' },
    { id: 'e68', source: 'm35', target: 'o12' },
    { id: 'e69', source: 'm35', target: 'o13' },
    { id: 'e70', source: 'm35', target: 'o14' },
    { id: 'e71', source: 'm35', target: 'o23' },
    { id: 'e72', source: 'm35', target: 'o24' },
    { id: 'e73', source: 'm35', target: 'o25' },
    { id: 'e74', source: 'm35', target: 'o26' },
    { id: 'e75', source: 'm36', target: 'm13' },
    { id: 'e76', source: 'm36', target: 'm14' },
    { id: 'e77', source: 'm36', target: 'm15' },
    { id: 'e78', source: 'm36', target: 'm19' },
    { id: 'e79', source: 'm36', target: 'm20' },
    { id: 'e80', source: 'm36', target: 'm32' },
    { id: 'e81', source: 'm36', target: 'm33' },
    { id: 'e82', source: 'm36', target: 'm34' },
    { id: 'e83', source: 'm36', target: 'm35' },
];