const op_labels = [
    'Taux de comptes conformes au principe "least privilege"',
    "Taux de comptes inactifs supprimés",
    'Taux d’implémentation du MFA',
    'Taux de revue des comptes à privilèges',
    'Taux de comptes génériques',
    'Temps moyen de révocation des accès',
    'Taux de données sensibles chiffrées',
    'Taux de couverture du DLP',
    'Taux d’assets critiques chiffrés',
    'Taux de couverture Antivirus',
    'Taux de couverture EDR',
    'Taux d’obsolescence global',
    'Taux d’obsolescence par systèmes',
    'Taux de systèmes critiques avec obsolescence critique',
    'Taux de dérogations contrôlées',
    'Taux de changements contrôlés',
    'Taux d’inspection du trafic sortant (messagerie)',
    'Taux de spams identifiés',
    'Nombre de spams remontés par les collaborateurs',
    'Taux de scan code source des applications',
    'Taux d’assets critiques contrôlés (Pentests/Scans)',
    'Taux de projets techniquement contrôlés avant MEP',
    'Taux de vulnérabilités pour les assets critiques',
    'Taux de couverture des scans de vulnérabilités',
    'Nombre de vulnérabilités enregistrées par sévérité',
    'Répartition des vulnérabilités identifiées par catégorie',
    'Taux de correction des vulnérabilités',
    'Taux de couverture SOC global',
    'Taux de couverture SOC par catégorie d’assets',
    'Répartition des incidents par étape MITRE ATT&CK',
    'Répartition des incidents par criticité',
    'Répartition des incidents collectés par typologie',
    'Taux de faux positifs',
    'Taux de prise en charge des alertes dans les délais',
    'Taux de traitement des incidents dans les délais',
    'Temps moyen de qualification des incidents',
    'Temps moyen de traitement des incidents',
    'Temps moyen de mise en place des plans de mitigation',
    'Taux de remontées avérées couvertes par SOP',
    'Taux d’incidents de sécurité du Cloud externe',
    'Taux de couverture des uses cases actuels',
    'Taux d’implémentation des uses cases SIEM',
]

let op_nodes = [];
for (let i = 0; i < op_labels.length; i++) {
    op_nodes.push({
        id: `o${i + 1}`,
        type: "kpiNode",
        data: {
            label: op_labels[i],
            category: 'operational',
        },
        parentId: 'operational',
        extent: 'parent',
    });
}

const managerial_labels = [
    'Taux de conformité par loi et norme SSI',
    'Taux d’avancement des travaux de revue des lois et normes',
    'Taux d’avancement des chantiers de mise/maintien en conformité',
    'Taux de conformité à la PSI Entreprise et directives internes',
    'Taux de revue de la PSI et directives internes',
    'Niveau de maturité cyber (ISO27001)',
    'Taux de suivi global des sessions de sensibilisation SSI',
    'Taux de réalisation de la feuille de route de sensibilisation',
    'Taux de réussite au questionnaire SSI',
    'Taux d’échecs aux campagnes phishing',
    'Taux de collaborateurs ayant fourni des infos sensibles (phishing)',
    'Taux de collaborateurs ayant remonté une alerte (phishing)',
    'Statut de l’analyse de risque SSI',
    'Taux de couverture des risques par famille',
    'Taux de couverture des risques par criticité',
    'Taux d’avancement des plans de traitement des risques',
    'Taux de contribution des use cases à la couverture des risques',
    'Répartition des données Cloud par criticité',
    'Taux d’intégration de la sécurité dans les projets',
    'Taux d’analyse de risque SSI projet',
    'Taux de conformité global des scans code source',
    'Taux des tiers évalués avant contractualisation',
    'Score moyen des tiers pré-contractualisation',
    'Taux de prestataires critiques audités',
    'Score moyen SSI des tiers critiques post-audit',
    'Turnover des ressources SSI internes',
    'Charge prévisionnelle du pôle SSI',
    'Répartition de la charge globale (BUILD/RUN)',
    'Forecast du pôle SSI',
    'Suivi global du statut des projets SSI',
    'Suivi des 5 projets SSI phares',
    'Indice de performance de la fonction de détection',
    'Indice de performance de la fonction de réaction',
    'Indice de protection des assets',
    'Indice de perméabilité',
    'Indice d’exposition aux risques cyber',
]

let managerial_nodes = [];
for (let i = 0; i < managerial_labels.length; i++) {
    managerial_nodes.push({
        id: `m${i + 1}`,
        type: "kpiNode",
        data: {
            label: managerial_labels[i],
            category: 'managerial',
        },
        parentId: 'managerial',
        extent: 'parent',
    });
}

const strategic_labels = [
    'Indice de Performance de la fonction de Détection',
    'Indice de Performance de la fonction de Réaction',
    'Indice de Protection des assets',
    'Indice de Perméabilité',
    "Indice d’exposition aux risques cyber",
    'Part budget dédié à la sécurité SI vs pratiques marché',
    'Répartition budget CAPEX - OPEX',
    'Répartition du budget cyber par domaine',
    'Consommation du budget run vs build',
    'Return On Security Investments (ROSI) d’une solution déployée',
    'Taux de conformité global aux lois et normes SSI',
    'Taux de conformité par loi et normes SSI',
    'Niveau de maturité cyber par rapport au référentiel ISO27001',
    'Suivi global du statut des projets/programmes au niveau du pôle',
    'Taux d’intégration de la sécurité au niveau des projets (SI, réseau, digital)',
    'Taux de couverture SOC global',
    'Taux de couverture des uses cases actuels',
    'Taux d’implémentation des uses cases',
    'Taux de faux positifs',
    'Taux de remontées avérées couvertes par une procédure standard de réaction (SOP)',
    'Temps moyen de mise en place des plans de mitigation des incidents',
    'Taux de prise en charge des alertes dans les délais',
    'Taux de traitement des incidents dans les délais',
    'Taux de couverture des solutions Antivirus avec version à jour',
    'Taux de couverture de solutions EDR au niveau des endpoints',
    'Taux d’implémentation du MFA',
    'Taux de couverture des scans de sécurité et tests d’intrusion',
    'Taux de spams remontés par les collaborateurs',
    'Taux d’obsolescence global',
    'Taux de vulnérabilités pour les assets critiques',
    'Taux de systèmes critiques avec obsolescence critique',
    'Statut de l’analyse de risque SSI',
    'Taux de risques critiques non couverts',
    'Taux de suivi global des sessions sensibilisations SSI',
]
let strategic_nodes = [];
for (let i = 0; i < strategic_labels.length; i++) {
    strategic_nodes.push({
        id: `s${i + 1}`,
        type: "kpiNode",
        data: {
            label: strategic_labels[i],
            category: 'strategic',
        },
        parentId: 'strategic',
        extent: 'parent',
    });
}

export const initialNodes = [
    {
        id: 'strategic',
        type: 'group',
        data: {
            category: 'Strategic',
            type: 'group',
        },
        position: { x: 0, y: -480 },
        style: { width: 2500, height: 430, backgroundColor: 'rgba(0, 255, 0, 0.2)' },
        draggable: false
    },
    {
        id: 'managerial',
        type: 'group',
        data: {
            category: 'Managerial',
            type: 'group',
        },
        position: { x: 0, y: 0 },
        style: { width: 2500, height: 430, backgroundColor: 'rgba(0, 0, 255, 0.1)' },
        draggable: false
    },
    {
        id: 'operational',
        type: 'group',
        data: {
            category: 'Operational',
            type: 'group',
        },
        position: { x: 0, y: 480 },
        style: { width: 2500, height: 430, backgroundColor: 'rgba(255, 0, 0, 0.1)' },
        draggable: false
    },
    ...op_nodes,
    ...managerial_nodes,
    ...strategic_nodes,
];

export const initialEdges = [
    { id: 'e1', source: 'm10', target: 'm11' },
    { id: 'e2', source: 'm10', target: 'm12' },
    { id: 'e3', source: 'm13', target: 'o17' },
    { id: 'e4', source: 'm13', target: 'o20' },
    { id: 'e5', source: 'm13', target: 'o21' },
    { id: 'e6', source: 'm13', target: 'o22' },
    { id: 'e7', source: 'm13', target: 'o27' },
    { id: 'e8', source: 'm13', target: 'o28' },
    { id: 'e9', source: 'm13', target: 'o33' },
    { id: 'e10', source: 'm14', target: 'o1' },
    { id: 'e11', source: 'm14', target: 'o2' },
    { id: 'e12', source: 'm14', target: 'o7' },
    { id: 'e13', source: 'm14', target: 'o8' },
    { id: 'e14', source: 'm14', target: 'o9' },
    { id: 'e15', source: 'm14', target: 'o10' },
    { id: 'e16', source: 'm14', target: 'o11' },
    { id: 'e17', source: 'm14', target: 'o17' },
    { id: 'e18', source: 'm14', target: 'o18' },
    { id: 'e19', source: 'm14', target: 'o30' },
    { id: 'e20', source: 'm14', target: 'o31' },
    { id: 'e21', source: 'm14', target: 'o32' },
    { id: 'e22', source: 'm15', target: 'o1' },
    { id: 'e23', source: 'm15', target: 'o2' },
    { id: 'e24', source: 'm15', target: 'o7' },
    { id: 'e25', source: 'm15', target: 'o8' },
    { id: 'e26', source: 'm15', target: 'o9' },
    { id: 'e27', source: 'm15', target: 'o10' },
    { id: 'e28', source: 'm15', target: 'o11' },
    { id: 'e29', source: 'm15', target: 'o17' },
    { id: 'e30', source: 'm15', target: 'o18' },
    { id: 'e31', source: 'm15', target: 'o30' },
    { id: 'e32', source: 'm15', target: 'o31' },
    { id: 'e33', source: 'm15', target: 'o32' },
    { id: 'e34', source: 'm16', target: 'o8' },
    { id: 'e35', source: 'm16', target: 'o10' },
    { id: 'e36', source: 'm16', target: 'o11' },
    { id: 'e37', source: 'm16', target: 'o24' },
    { id: 'e38', source: 'm16', target: 'o28' },
    { id: 'e39', source: 'm16', target: 'o34' },
    { id: 'e40', source: 'm16', target: 'o35' },
    { id: 'e41', source: 'm16', target: 'o36' },
    { id: 'e42', source: 'm16', target: 'o37' },
    { id: 'e43', source: 'm16', target: 'o38' },
    { id: 'e44', source: 'm17', target: 'o41' },
    { id: 'e45', source: 'm19', target: 'o22' },
    { id: 'e46', source: 'm19', target: 'm20' },
    { id: 'e47', source: 'm21', target: 'o20' },
    { id: 'e48', source: 'm23', target: 'm22' },
    { id: 'e49', source: 'm30', target: 'm2' },
    { id: 'e50', source: 'm30', target: 'm3' },
    { id: 'e51', source: 'm32', target: 'o33' },
    { id: 'e52', source: 'm33', target: 'o34' },
    { id: 'e53', source: 'm33', target: 'o35' },
    { id: 'e54', source: 'm33', target: 'o36' },
    { id: 'e55', source: 'm33', target: 'o37' },
    { id: 'e56', source: 'm33', target: 'o38' },
    { id: 'e57', source: 'm33', target: 'o39' },
    { id: 'e58', source: 'm33', target: 'o40' },
    { id: 'e59', source: 'm34', target: 'o3' },
    { id: 'e60', source: 'm34', target: 'o7' },
    { id: 'e61', source: 'm34', target: 'o8' },
    { id: 'e62', source: 'm34', target: 'o9' },
    { id: 'e63', source: 'm34', target: 'o10' },
    { id: 'e64', source: 'm34', target: 'o11' },
    { id: 'e65', source: 'm34', target: 'o24' },
    { id: 'e66', source: 'm34', target: 'o28' },
    { id: 'e67', source: 'm34', target: 'o29' },
    { id: 'e68', source: 'm35', target: 'o12' },
    { id: 'e69', source: 'm35', target: 'o13' },
    { id: 'e70', source: 'm35', target: 'o14' },
    { id: 'e71', source: 'm35', target: 'o23' },
    { id: 'e72', source: 'm35', target: 'o24' },
    { id: 'e73', source: 'm35', target: 'o25' },
    { id: 'e74', source: 'm35', target: 'o26' },
    { id: 'e75', source: 'm36', target: 'm13' },
    { id: 'e76', source: 'm36', target: 'm14' },
    { id: 'e77', source: 'm36', target: 'm15' },
    { id: 'e78', source: 'm36', target: 'm19' },
    { id: 'e79', source: 'm36', target: 'm20' },
    { id: 'e80', source: 'm36', target: 'm32' },
    { id: 'e81', source: 'm36', target: 'm33' },
    { id: 'e82', source: 'm36', target: 'm34' },
    { id: 'e83', source: 'm36', target: 'm35' },
];